### ISSUE TITLE
Reproducing results from the paper

### ISSUE THREAD

**Issue by Wayne2Wang** [vlfom/rncdl#2]
Dear authors,

Thank you for publishing your code for the great work! The code is easily readable and well structured, but I do have a few minor questions about it:

1. It was mentioned in the paper that you used a Lognormal prior with an std of 0.5 in the SinkhornKnopp algorithm. However, it seems like the code uses 0.1, which was set to the default value and never changed in the config files. I wonder which value you would recommend using to reproduce the results.
2. As was pointed out by a previous issue, the `it180k_bs16.py` file is missing inside the `configs.train.fully_supervised` folder. I was able to write my own version of it according to the descriptions in the paper, but I would appreciate it if an official version could be provided.

Many thanks for considering my request.

**Comment by vlfom** [comment]
Dear Wang,

I apologize for my late reply. Please find the responses below.

1. Indeed, we have used `std=0.5` in our experiments, thank you for spotting this. We forgot to modify it in the code when cleaning up the project. I have updated the default value to `0.5`.

2. Thank you for reporting this bug. When cleaning up the code we forgot to rename the configuration files. It has now been fixed.

To help reproduce the results, I have now revisited the `ReadME` file and made sure that the instructions are correct, and the results are reproducible from the provided code in a fresh environment. As too many things have changed, please check the instructions again to make sure you have followed the right steps, as there were many things missing before, for example, a requirement to modify some `detectron2` library files inplace. Also, make sure to `git pull` the latest commit. We have also uploaded model checkpoints - both fully supervised and discovery ones. Finally, we have provided better instructions for LVIS + VisualGenome setup.

Please let me know in case you face any other issues.

**Comment by Wayne2Wang** [comment]
Thanks for your reply! Everything is crystal clear now.

It took me 5-6 hours to run the evaluation for the discovery model, but what you mentioned in `Readme` would definitely help.
