### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by devendraswamy** [vlfom/rncdl#5]
Hi , Please let me know, is this project supports to windows deployment for inference , Thanking you in advance.

**Comment by vlfom** [comment]
Hi devendraswamy,

Our implementation is based on [Detectron2](https://github.com/facebookresearch/detectron2) which is a flexible platform for object detection. It is available on all platforms and their repository and wiki contain extensive installation documentation. Once you have trained the network using our method, you could follow Detectron2 guidelines for any special use cases you have in mind. Our focus was on quantitative evaluation and in our repository we only include code to calculate mAP once the network is trained.

Hope this helps!
