### ISSUE TITLE
Questions about COCO-half in discovery phase

### ISSUE THREAD

**Issue by slcheng97** [vlfom/rncdl#6]
I have run your code for the supervised training phase and discovery phase, but I found that you didn't use another unlabeled half-coco data during the discovery phase. I wonder if I missed some details here. Could you point out where you use another unlabeled half-coco training data in your codebase?

**Comment by vlfom** [comment]
Hi chengsilin,

The way we use the rest of COCO images is via using LVIS dataset "default" configuration that includes 100% of COCO images.

In [line 70](https://github.com/vlfom/RNCDL/blob/45f650c84273d232448336dd2a30beacff2a6663/configs/train/discovery/coco50pct_lvis.py#L70) of `configs/train/discovery/coco50pct_lvis.py` we define the "discovery data loader" as:
```python
proposals_dataloader = L(build_detection_train_loader)(
    dataset=L(get_detection_dataset_dicts)(names="lvis_v1_train", filter_empty=False),
    ...
)
```

This means that for the discovery loop we will use all images from the LVIS dataset that include 100% of COCO images respectively.

**Comment by vlfom** [comment]
Please reopen the issue if you have any other questions.

**Comment by slcheng97** [comment]
Ok, I see. Thanks
