### ISSUE TITLE
Out of Memory Issues During Evaluation After Discovery Training

### ISSUE THREAD

**Issue by rohit901** [vlfom/rncdl#7]
Hello,

First of all thank you for releasing the code and for the paper. It is very well written and I found it to be very interesting.
I'm trying to replicate the method described. I was able to train the supervised and the discovery phase of the models. However after the discovery training is finished, I'm not able to evaluate the model as my SLURM job is getting cancelled due to Out of Memory issues.

The error logs shows this:
```
Traceback (most recent call last):
  File "tools/train_discovery.py", line 188, in <module>
    launch(
  File "/home/rohit.bharadwaj/.conda/envs/RNCDL/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/rohit.bharadwaj/.conda/envs/RNCDL/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/rohit.bharadwaj/.conda/envs/RNCDL/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/rohit.bharadwaj/.conda/envs/RNCDL/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 3 terminated with signal SIGKILL
slurmstepd-gpu-01: error: Detected 1 oom-kill event(s) in StepId=96363.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

Last few lines of output logs are:
```
[01/20 23:37:50 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333)]
[01/20 23:37:50 d2.data.common]: Serializing 19809 elements to byte tensors and concatenating them all ...
[01/20 23:37:51 d2.data.common]: Serialized dataset takes 199.94 MiB
```

I'm using 4 GPUs [NVIDIA A100, each with around 40GB Memory]. I'm not sure if the OOM issue is because other jobs are also scheduled in my assigned GPU or its because of this code/batch.

I have tried to change the batch size to 1 per GPU by making the following changes in `configs/train/discovery/coco50pct_lvis.py`

1. Line 55, changed to: 
`one_epoch_niter = int(100170 / 4)`
2. Line 79, changed to:
`total_batch_size=4,`
3. Line 82, changed to:
`model_supervised.roi_heads.box_predictor.discovery_model.batch_size = 1`
4. Line 102, changed to:
`batch_size=1,`
5. Line 115, changed to:
`batch_size=1,`

Even after the above changes, I'm still getting the OOM error. Could you please help me how to proceed with this and how can I get the evaluation results after both the supervised and discovery phase has finished training? I'm using COCO + LVIS data.

Thanks,
Rohit

**Comment by vlfom** [comment]
Dear Rohit,

I am very sorry for my late reply, I will try to follow this thread closer now.

I am thinking the issue could be due to lack of non-GPU memory. I believe the OOM could be due to Hungarian Matching procedure or other CPU-bound downstream operations. If you're using SLURM, could you try increasing your CPU RAM assigned?

I'll try thinking of other solutions, too.

**Comment by rohit901** [comment]
Thank you so much for your reply Vladimir.

I will try to increase the CPU ram and try again. I was earlier running the experiments by using 64 GB CPU RAM. I will try to increase it and report back if it helps.

Thanks.

**Comment by rohit901** [comment]
Hi Vladimir,

I increased the CPU ram to 128 GB, and the evaluation was completed successfully this time. Thank you so much for your suggestion, turns out low CPU ram (64GB) was the cause of the issue. 

I had some more doubts, could you please clarify them?

1. The AP metrics mentioned in the paper for COCO+LVIS is it for **segm** or **bbox** task?
2. I'm getting these results after discovery training. Comparing with the paper (**mAP_known** = 25.00, **mAP_all** = 6.92, **mAP_novel** = 5.42), I think my **mAP_known** is 24.107, **mAP_novel** = 4.356, **mAP_all** = 5.864?
```
[02/13 08:50:07 d2.evaluation.lvis_evaluation]: [Evaluator new] Evaluation results for segm: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl   |  APr  |  APc  |  APf  |
|:-----:|:------:|:------:|:-----:|:-----:|:------:|:-----:|:-----:|:-----:|
| 5.864 | 8.937  | 6.179  | 2.771 | 7.612 | 11.165 | 5.852 | 4.741 | 7.122 |

[02/13 08:50:07 d2.evaluation.lvis_evaluation]: Evaluation results for segm (known classes only): 
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |   APr    |   APc    |  APf   |
|:------:|:------:|:------:|:------:|:------:|:------:|:--------:|:--------:|:------:|
| 24.107 | 39.116 | 25.035 | 10.801 | 29.843 | 37.504 | -100.000 | -100.000 | 24.107 |

[02/13 08:50:07 d2.evaluation.lvis_evaluation]: Evaluation results for segm (novel classes only): 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |  APr  |  APc  |  APf  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 4.356 | 6.443  | 4.621  | 1.978 | 5.526 | 7.846 | 5.852 | 4.741 | 3.006 |

```

I'm using the same config/parameters/seed as in the given code, but not sure about the difference in results, am I doing something wrong?

**Comment by vlfom** [comment]
Hi Rohit, could you please share the command that you use for the 2nd phase of training?

Is it exactly the same command mentioned in ReadME.md under [#running-experiments](https://github.com/vlfom/RNCDL#running-experiments)?

After releasing the code, as sanity check, we have tried running that snippet on 8GPUs (with the same batch size) using `7500` iterations and obtained an mAP of ~7.35.

**Comment by rohit901** [comment]
This is the command being run in discovery phase training. I'm just using the commands given in the slurm_scripts folder in the repo.

Note i've added the from_discovery argument to resume training in discovery from 10k iterations. [my slurm cluster allows me only 12 hour consecutive jobs, so had to resume in discovery and supervised phase as well]

and made this small change in tools/train_discovery.py at the end of `do_train` function

```
    # # Train
    if cfg.train.weights_mode == "from_discovery":
        checkpointer.resume_or_load(cfg.train.init_checkpoint, resume=True)
        start_iter = trainer.iter + 1
    else:
        start_iter = 0
    # start_iter = 0
    trainer.train(start_iter, cfg.train.max_iter)
```

```
CONFIG_FILE="./configs/train/discovery/coco50pct_lvis.py"

CHECKPOINT_PATH="/slurm/slurm_runs/coco50pct_lvis-discover-mldvy/model_0009999.pth"

OUTPUT_DIR=/slurm/slurm_runs/coco50pct_lvis-discover-mldvy

PYTHONPATH="/home/rohit.bharadwaj/Projects/RNCDL" python tools/train_discovery.py \
    \
    --config-file $CONFIG_FILE \
    --num-gpus 4 \
    --dist-url 'tcp://localhost:10042' \
    \
    train.exp_name="coco50pct_lvis-discovery" \
    train.output_dir=$OUTPUT_DIR \
    train.init_checkpoint=$CHECKPOINT_PATH \
    train.eval_period=999999 \
    discovery_evaluator.evaluator.output_dir=$OUTPUT_DIR \
    \
    train.max_iter=15000 \
    optimizer.lr=0.01 \
    train.seed=42 \
    train.weights_mode="from_discovery" \
    \
    model_proposals_extraction_param.test_nms_thresh=1.01 \
    model_proposals_extraction_param.test_topk_per_image=50 \
    \
    train.supervised_loss_lambda=0.5 \
    \
    model_supervised.roi_heads.box_predictor.discovery_model.num_unlabeled=3000 \
    model_supervised.roi_heads.box_predictor.discovery_model.sk_mode="lognormal" \
    \
    model_supervised.roi_heads.box_predictor.discovery_model.memory_batches=100 \
    model_supervised.roi_heads.box_predictor.discovery_model.memory_patience=150
```

**Comment by vlfom** [comment]
I see. It seems like the algorithm is very sensitive to the setup, incl. number of GPUs and number of steps, which is unfortunate, and was not reflected in the paper, indeed.

Could you try evaluating the 10K checkpoint, too, please?

**Comment by rohit901** [comment]
Tried to evaluate on the 10k checkpoint and the results seem worse. Also just wanted to verify that we are comparing the segm results right and these values obtained directly from the logs show the mAP values only?

```
[02/21 03:17:59 d2.evaluation.lvis_evaluation]: [Evaluator new] Evaluation results for segm: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl   |  APr  |  APc  |  APf  |
|:-----:|:------:|:------:|:-----:|:-----:|:------:|:-----:|:-----:|:-----:|
| 5.384 | 8.431  | 5.616  | 2.662 | 7.611 | 10.451 | 3.973 | 4.241 | 7.279 |
[02/21 03:17:59 d2.evaluation.lvis_evaluation]: Evaluation results for segm (known classes only): 
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |   APr    |   APc    |  APf   |
|:------:|:------:|:------:|:------:|:------:|:------:|:--------:|:--------:|:------:|
| 24.840 | 40.584 | 25.696 | 11.450 | 31.112 | 37.928 | -100.000 | -100.000 | 24.840 |
[02/21 03:17:59 d2.evaluation.lvis_evaluation]: Evaluation results for segm (novel classes only): 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |  APr  |  APc  |  APf  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 3.776 | 5.774  | 3.956  | 1.794 | 5.406 | 6.989 | 3.973 | 4.241 | 3.023 |
```

**Comment by vlfom** [comment]
Hi Rohit,

Thank you for checking this, it's unfortunate the scores are still low. Let me think more about what could be wrong and check the parameters again. Unfortunately, the codebase cleanup seem to have affected performance a bit.

I just realized that I missed point 1 from your comment above. In our paper we actually focus on optimizing the **bbox task** scores, while **segm task** scores are reported in Appendix only, and they are a bit lower. Thus, your **bbox** results should be a bit closer to the `6.92` reported in our manuscript. I can guess that your current **bbox** score is likely ~`6` mAP. 

This is still lower than ~`7` mAP obtained in my experiments, though, and I can confirm I have taken these values directly from console, similar to how you demonstrated it here, so I will look more into this.

**Comment by rohit901** [comment]
Hi Vladimir,
Thank you for your reply and for the confirmation.
I checked the bbox task scores and they are as follows:

```
[02/13 08:40:07 d2.evaluation.lvis_evaluation]: [Evaluator new] Evaluation results for bbox: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl   |  APr  |  APc  |  APf  |
|:-----:|:------:|:------:|:-----:|:-----:|:------:|:-----:|:-----:|:-----:|
| 6.243 | 9.662  | 6.501  | 3.275 | 8.001 | 10.831 | 6.560 | 5.194 | 7.274 |
[02/13 08:40:07 d2.evaluation.lvis_evaluation]: Evaluation results for bbox (known classes only): 
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |   APr    |   APc    |  APf   |
|:------:|:------:|:------:|:------:|:------:|:------:|:--------:|:--------:|:------:|
| 23.961 | 40.740 | 23.917 | 12.596 | 30.285 | 32.231 | -100.000 | -100.000 | 23.961 |
[02/13 08:40:07 d2.evaluation.lvis_evaluation]: Evaluation results for bbox (novel classes only): 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |  APr  |  APc  |  APf  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 4.779 | 7.094  | 5.062  | 2.355 | 5.910 | 8.135 | 6.560 | 5.194 | 3.230 |
```
There still seems to be some difference from those from the paper right?

Thank you so much for looking into this issue and for your assistance.

**Comment by vlfom** [comment]
Hi Rohit,

I have looked into the discrepancy between your score of `6.24` and the scores we reported in the paper (`6.92`) and in the ReadME (`7.35`) again and I believe the main reason for the difference with the scores from ReadME, that used exactly the same codebase, is the number of GPUs used for training.

Due to the way we implemented the local proposals-memory, each GPU instance has its own separate memory, so the "effective" number of stored proposals at each iteration is `n_gpus * memory_size`. This means that with more GPUs, the loss and the resulting gradients are likely to be less noisy and more stable, leading to better performance.

Therefore, even when using exactly the same parameters, but different number of GPUs, you may achieve different results. This is an important factor that we did not explicitly mention in our paper or ReadME, I apologize for confusion. If you have access to 8x GPUs, could you please try running the script from the ReadME, e.g. for `7500` -> `7500` more steps, and checking the results?

We will try to provide more guidance and clarity on how to reproduce our results with different hardware settings in future revisions, if any.

**Comment by rohit901** [comment]
Thank you once again for your reply and for spending time going through this issue with me Vladimir. 

I thought the number of GPUs used in the paper is 4 right? Could you please confirm this aspect? Because in my results reported so far I have been using 4x Nvidia A100 GPUs as well. So I thought the number of GPUs would be same with those used in paper and in my experiments?

I will try to see if I can have access to 8 GPUs but currently only have access to 4.

Thank you once again for your comments.

**Comment by vlfom** [comment]
Hi Rohit, 

In the paper we have used 4 GPUs, but due to cleanup, something has changed in the code, hence you get the `6.243` result, different from our manuscript. Unfortunately, I believe the change is impossible to track, so our `6.92` result is not reproducible.

However, the new, better result of `7.35`, mentioned in ReadME, was obtained using 8 GPUs, using current codebase.

**Comment by rohit901** [comment]
Ahh I see, thank you for the clarification Vladimir. That makes sense. I would also like to thank you for clarifying some of the aspects to me. If you wish to, you can close this issue.
